import { db } from '@/lib/db';
import { notFound } from 'next/navigation';

// Force dynamic rendering - this allows newly generated websites to be accessible
export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function SitePage({ 
  params 
}: { 
  params: Promise<{ id: string }> 
}) {
  try {
    const { id } = await params;
    
    console.log('[SitePage] Loading website:', id);
    
    const website = await db.website.findFirst({
      where: {
        id,
        status: 'COMPLETED'
      }
    });
    
    if (!website) {
      console.log('[SitePage] Website not found:', id);
      notFound();
    }
    
    if (!website.htmlContent) {
      console.log('[SitePage] No HTML content for:', id);
      notFound();
    }
    
    console.log('[SitePage] Rendering website:', website.title);
    
    return (
      <div 
        dangerouslySetInnerHTML={{ __html: website.htmlContent }}
      />
    );
  } catch (error) {
    console.error('[SitePage] Error:', error);
    notFound();
  }
}

// Metadata for SEO
export async function generateMetadata({ 
  params 
}: { 
  params: Promise<{ id: string }> 
}) {
  try {
    const { id } = await params;
    
    const website = await db.website.findFirst({
      where: { id }
    });
    
    return {
      title: website?.title || 'Website - space.z.ai',
      description: website?.description || 'Generated by space.z.ai',
    };
  } catch {
    return {
      title: 'Website - space.z.ai',
      description: 'Generated by space.z.ai',
    };
  }
}
