import { db } from '@/lib/db';
import { notFound } from 'next/navigation';
import Link from 'next/link';

// Force dynamic rendering
export const dynamic = 'force-dynamic';
export const revalidate = 0;

export default async function WebsitePage({ 
  params 
}: { 
  params: Promise<{ id: string }> 
}) {
  try {
    const { id } = await params;
    
    console.log('[WebsitePage] Loading website:', id);
    
    const website = await db.website.findFirst({
      where: {
        id,
        status: 'COMPLETED'
      }
    });
    
    // If website not found or no content
    if (!website || !website.htmlContent) {
      console.log('[WebsitePage] Website not found or no content:', id);
      
      return (
        <html lang="id">
          <head>
            <meta charSet="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>Website Tidak Ditemukan - space.z.ai</title>
            <style dangerouslySetInnerHTML={{ __html: `
              * { margin: 0; padding: 0; box-sizing: border-box; }
              body { 
                font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                background: linear-gradient(135deg, #3B82F6 0%, #8B5CF6 100%);
                color: white;
                padding: 20px;
              }
              .container {
                text-align: center;
                max-width: 500px;
              }
              .icon {
                width: 80px;
                height: 80px;
                background: rgba(255,255,255,0.2);
                border-radius: 50%;
                display: flex;
                align-items: center;
                justify-content: center;
                margin: 0 auto 24px;
                font-size: 40px;
              }
              h1 { font-size: 28px; margin-bottom: 16px; font-weight: 700; }
              p { opacity: 0.9; margin-bottom: 24px; line-height: 1.6; }
              a {
                display: inline-block;
                background: white;
                color: #3B82F6;
                padding: 12px 32px;
                border-radius: 12px;
                text-decoration: none;
                font-weight: 600;
                transition: transform 0.2s, box-shadow 0.2s;
              }
              a:hover {
                transform: translateY(-2px);
                box-shadow: 0 10px 30px rgba(0,0,0,0.2);
              }
            ` }} />
          </head>
          <body>
            <div className="container">
              <div className="icon">📄</div>
              <h1>Website Tidak Ditemukan</h1>
              <p>
                Website yang Anda cari tidak ditemukan atau belum selesai diproses.
                <br />
                Pastikan website sudah berhasil dibuat.
              </p>
              <Link href="/">Kembali ke Beranda</Link>
            </div>
          </body>
        </html>
      );
    }
    
    console.log('[WebsitePage] Rendering website:', website.title);
    
    // Return the HTML content directly
    return (
      <div 
        dangerouslySetInnerHTML={{ __html: website.htmlContent }}
      />
    );
  } catch (error) {
    console.error('[WebsitePage] Error:', error);
    notFound();
  }
}

// Metadata for SEO
export async function generateMetadata({ 
  params 
}: { 
  params: Promise<{ id: string }> 
}) {
  try {
    const { id } = await params;
    
    const website = await db.website.findFirst({
      where: { id }
    });
    
    return {
      title: website?.title || 'Website - space.z.ai',
      description: website?.description || 'Generated by space.z.ai',
    };
  } catch {
    return {
      title: 'Website - space.z.ai',
      description: 'Generated by space.z.ai',
    };
  }
}
